# Generated by Django 4.2.16 on 2024-11-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_is_anonymous_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_anonymous',
        ),
    ]
